# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
  
  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: npm run package
    - name: upload package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: migrations-talk/

  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
    - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: package
    - name: Upload binary to S3 bucket
      uses: tpaschalis/s3-cp-action@v0.2.0
      with:
        args: --acl public-read
    env:
      FILE: migrations-talk/
      AWS_REGION: 'ap-southeast-2'
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
